admin_act_valide_index:
    path:     /
    defaults: { _controller: "ActiviteBundle:valideAdmin:index" }
    methods:  GET

admin_act_valide_show:
    path:     /{id}/show
    defaults: { _controller: "ActiviteBundle:valideAdmin:show" }
    methods:  GET

admin_act_valide_new:
    path:     /new
    defaults: { _controller: "ActiviteBundle:valideAdmin:new" }
    methods:  [GET, POST]

admin_act_valide_edit:
    path:     /{id}/edit
    defaults: { _controller: "ActiviteBundle:valideAdmin:edit" }
    methods:  [GET, POST]

admin_act_valide_delete:
    path:     /{id}/delete
    defaults: { _controller: "ActiviteBundle:valideAdmin:delete" }
    methods:  DELETE
