admin_Categories:
    path:  /
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:index" }

adminCategories_show:
    path:  /{id}/show
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:show" }

adminCategories_new:
    path:  /new
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:new" }

adminCategories_create:
    path:  /create
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:create" }
    requirements: { _method: post }

adminCategories_edit:
    path:  /{id}/edit
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:edit" }

adminCategories_update:
    path:  /{id}/update
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:update" }
    requirements: { _method: post|put }

adminCategories_delete:
    path:  /{id}/delete
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:delete" }
    requirements: { _method: post|delete }
