adminPages:
    path:  /
    defaults: { _controller: "PagesBundle:PagesAdmin:index" }

adminPages_softdel:
    path:  /soft/del
    defaults: { _controller: "PagesBundle:PagesAdmin:softDel" }

adminPages_restore:
    path:  /{id}/restore
    defaults: { _controller: "PagesBundle:PagesAdmin:restore" }
    
adminPages_show:
    path:  /{id}/show
    defaults: { _controller: "PagesBundle:PagesAdmin:show" }

adminPages_new:
    path:  /new
    defaults: { _controller: "PagesBundle:PagesAdmin:new" }

adminPages_create:
    path:  /create
    defaults: { _controller: "PagesBundle:PagesAdmin:create" }
    requirements: { _method: post }

adminPages_edit:
    path:  /{id}/edit
    defaults: { _controller: "PagesBundle:PagesAdmin:edit" }

adminPages_update:
    path:  /{id}/update
    defaults: { _controller: "PagesBundle:PagesAdmin:update" }
    requirements: { _method: post|put }

adminPages_delete:
    path:  /{id}/delete
    defaults: { _controller: "PagesBundle:PagesAdmin:delete" }
    requirements: { _method: post|delete }
