<?php

namespace Activite\ActiviteBundle\Repository;

/**
 * ancienneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aimeRepository extends \Doctrine\ORM\EntityRepository
{
	    public function byLiked($user, $album)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.user = :user')
                    ->andWhere('u.album = :album')
                    ->orderBy('u.id')
                    ->setParameter('user', $user)->setParameter('album',$album);
        return $qb->getQuery()->getResult();
    }
    
}
