<?php

namespace Activite\ActiviteBundle\Repository;

/**
 * ancienneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dateenvoteRepository extends \Doctrine\ORM\EntityRepository
{
}
