<?php

namespace Activite\ActiviteBundle\Repository;

/**
 * ideeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ideeRepository extends \Doctrine\ORM\EntityRepository
{
}
