<?php

namespace Activite\ActiviteBundle\Repository;

/**
 * valideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class valideRepository extends \Doctrine\ORM\EntityRepository
{
}
