parameters:
#    utilisateurs.example.class: Utilisateurs\UtilisateursBundle\Example

services:
#    utilisateurs.example:
#        class: %utilisateurs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    app.form.registration:
        class: UtilisateursBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }